repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - chart: prometheus-community/prometheus
    name: prometheus
    values:
     - prometheus.yaml
  - chart: grafana/loki-simple-scalable
    name: loki
    values:
     - loki.yaml
     