apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: metrics-servers
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/pv0001/