#kube-prometheus-stack configs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/masebb/metrics-server.git'
    path: configs/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
---
#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 45.7.1
      helm:
          valueFiles:
            - $myRepo/values/kube-prometheus-stack.yaml
    - repoURL: 'https://github.com/masebb/metrics-server.git'
      targetRevision: HEAD
      ref: myRepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated: {}
---
#alertmanager-discord
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-discord
  namespace: argocd
spec:
  project: default
  source:
    chart: alertmanager-discord
    repoURL: 'https://specklesystems.github.io/alertmanager-discord/stable/'
    targetRevision: 0.2.3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}