kind: Namespace
apiVersion: v1
metadata:
  name: metrics-servers
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs-pv
#   namespace: metrics-servers
# spec:
#   capacity:
#     storage: 40Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Recycle
#   nfs:
#     server: 02cluster1v.subnet1.vcn01231245.oraclevcn.com
#     path: /k8s-pv
#     readOnly: false
---
#prometheus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/masebb/metrics-server.git'
    path: prometheus/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-servers
  syncPolicy:
    automated: {}
---
#alertmanager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus-community/alertmanager
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 0.25.0
      helm:
        valueFiles:
          - $myRepo/alertmanager-values.yaml
    - repoURL: 'https://github.com/masebb/metrics-server.git'
      targetRevision: HEAD
      ref: myRepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-servers
  syncPolicy:
    automated: {}
---
#alertmanager-discord
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-discord
  namespace: argocd
spec:
  project: default
  source:
    chart: alertmanagerdiscord/alertmanager-discord
    repoURL: 'https://specklesystems.github.io/alertmanager-discord/stable/'
    targetRevision: 0.2.3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-servers
  syncPolicy:
    automated: {}