apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
#kube-prometheus-stack configs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/masebb/metrics-server.git'
    path: configs/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
---
#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 45.7.1
      helm:
        valueFiles:
          - $myRepo/values/kube-prometheus-stack.yaml
    - repoURL: 'https://github.com/masebb/metrics-server.git'
      targetRevision: HEAD
      ref: myRepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated: {}
---
#alertmanager-discord
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-discord
  namespace: argocd
spec:
  project: default
  sources:
    - chart: alertmanager-discord
      repoURL: 'https://masgustavos.github.io/helm'
      targetRevision: 0.2.3
      helm:
        valueFiles:
          - $myRepo/values/alertmanager-discord.yaml
    - repoURL: 'https://github.com/masebb/metrics-server.git'
      targetRevision: HEAD
      ref: myRepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
