apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-servers
resources:
  - deployment.yaml
  - service.yaml
  - config/prometheus/prometheus.yaml
  - config/prometheus/targets.yaml
  - config/prometheus/rules/blackbox.yaml
  - config/prometheus/rules/cadvisor.yaml
  - config/prometheus/rules/node.yaml
  - config/prometheus/rules/prometheus.yaml