apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-servers
resources:
  - deployment.yaml
  - service.yaml
  - config/file_sd_configs/*.yaml
  - config/rules/*.yaml
  - setup/*.yaml