apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: metrics-servers
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 02cluster1v.subnet1.vcn01231245.oraclevcn.com
    path: /k8s-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: metrics-servers
spec:
  selector:
    matchLabels:
      name: nfs-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
