apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: metrics-servers
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
    rule_files:
      - rules/*.yml
      - rules/*.yaml
    # alerting:
    #   alertmanagers:
    #     - scheme: http
    #       static_configs:
    #         - targets:
    #           - 10.1.1.3:9093
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]
      - job_name: 'node-exporter'
        scrape_interval: 15s
        file_sd_configs:
          - files:
            - sd_node.yaml
        relabel_configs:
          - source_labels: [__address__]
            target_label: __address__
            replacement: $1:9100
    #      - source_labels: [__address__]
    #        target_label: __param_target
    #      - source_labels: [__param_target]
    #        target_label: instance
      - job_name: "alertmanager"
        static_configs:
        - targets: ["10.1.1.3:9093"]
      - job_name: "cadvisor"
        scrape_interval: 15s
        file_sd_configs:
          - files:
            - sd_cadvisor.yaml
      - job_name: "blackbox_icmp"
        scrape_interval: 5s
        file_sd_configs:
          - files:
            - sd_node.yaml
            - sd_snmp_ifmib.yaml
         #   - sd_icmp_global.yaml
        metrics_path: /probe
        params:
          module: [icmp]
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 10.0.0.3:9115
      - job_name: "smoke-ping"
        scrape_interval: 5m
        static_configs:
        - targets: ["10.0.0.3:9374"]
      - job_name: "snmp_if_mib"
        file_sd_configs:
        - files:
          - sd_snmp_ifmib.yaml
          - sd_snmp_nec_ix.yaml
        metrics_path: /snmp
        params:
          module: [if_mib]
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 10.0.0.3:9116
      - job_name: "snmp_nec_ix"
        file_sd_configs:
          - files:
            - sd_snmp_nec_ix.yaml
        metrics_path: /snmp
        params:
          module: [nec_ix]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 10.0.0.3:9116
      - job_name: "nut"
        static_configs:
          # Insert NUT server address here
          - targets: ["10.0.0.3:3493"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            # Insert NUT exporter address here
            replacement: 10.0.0.3:9995
      - job_name: "promtail"
        scrape_interval: 15s
        file_sd_configs:
          - files:
            - sd_node.yaml
        relabel_configs:
          - source_labels: [__address__]
            target_label: __address__
            replacement: $1:9080
    #      - source_labels: [__address__]
    #        target_label: __param_target
    #      - source_labels: [__param_target]
    #        target_label: instance

